on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+.*'
name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - uses: lannonbr/vsce-action@master
        with:
          args: "package"
        env:
          VSCE_TOKEN: ${{ secrets.AZURE_DEVOPS_TESTYTS_TOKEN }}

      - uses: lannonbr/vsce-action@master
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.AZURE_DEVOPS_TESTYTS_TOKEN }}
